version: '2'
services:
    multic-app:
        image: multic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://multic-mysql:3306/multic?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    multic-mysql:
        extends:
            file: mysql.yml
            service: multic-mysql
